<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\Payment;
use App\Models\Reservation;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        User::query()->updateOrCreate([
            'email' => 'admin@bestrent.com',
        ], [
            'name' => 'Admin',
            'phone_number' => '+36301234567',
            'password' => 'password',
            'is_admin' => true,
        ]);

        User::query()->updateOrCreate([
            'email' => 'user@bestrent.com',
        ], [
            'name' => 'Felhasználó',
            'phone_number' => '+36201234567',
            'password' => 'password',
            'is_admin' => false,
        ]);

        User::query()->updateOrCreate([
            'email' => 'anna@bestrent.com',
        ], [
            'name' => 'Nagy Anna',
            'phone_number' => '+36306667777',
            'password' => 'password',
            'is_admin' => false,
        ]);

        User::query()->updateOrCreate([
            'email' => 'peter@bestrent.com',
        ], [
            'name' => 'Kiss Péter',
            'phone_number' => '+36307778888',
            'password' => 'password',
            'is_admin' => false,
        ]);

        $cars = [
            [
                'brand' => 'Tesla',
                'model' => 'Model 3 Performance',
                'category' => 'Sedan',
                'year' => 2022,
                'plate_number' => 'TES-301',
                'color' => 'Fekete',
                'fuel_type' => 'Elektromos',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 42000.00,
                'status' => 'available',
                'image' => 'https://www.pngplay.com/wp-content/uploads/13/Tesla-Model-3-PNG-Images-HD.png',
                'image_type' => 'link',
                'description' => 'Modern elektromos szedán, hosszú hatótávval.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:35:19',
            ],
            [
                'brand' => 'Audi',
                'model' => 'S4',
                'category' => 'Sedan',
                'year' => 2021,
                'plate_number' => 'AUD-444',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 36000.00,
                'status' => 'available',
                'image' => 'https://carsales.pxcrush.net/car/spec/S0001Q8W.jpg?pxc_method=GravityFill&width=480&height=320&watermark=2124530066',
                'image_type' => 'link',
                'description' => 'Sportos, Kényelmes üzleti autó prémium felszereltséggel.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:34:57',
            ],
            [
                'brand' => 'BMW',
                'model' => '320i',
                'category' => 'Sedan',
                'year' => 2020,
                'plate_number' => 'BMW-320',
                'color' => 'Szürke',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 35000.00,
                'status' => 'available',
                'image' => 'https://s3-eu-west-1.amazonaws.com/photo-ref-carboatmedia-fr/Qk1X/U0VSSUUgMw==/397f0555ffb8ff53ea414de4e7f4bafd/MQ==/307f767efdc69f3d2b26bef5c0b514dc.png',
                'image_type' => 'link',
                'description' => 'Sportos vezetési élmény városi és országúti használatra.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:36:58',
            ],
            [
                'brand' => 'Mercedes',
                'model' => 'C200',
                'category' => 'Sedan',
                'year' => 2021,
                'plate_number' => 'MER-200',
                'color' => 'Ezüst',
                'fuel_type' => 'Dízel',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 39000.00,
                'status' => 'available',
                'image' => 'https://img.pcauto.com/model/images/touPic/my/Mercedes-Benz-C-Class_160_small.png',
                'image_type' => 'link',
                'description' => 'Elegáns belső tér és kényelmes futómű.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:42:58',
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'category' => 'Sedan',
                'year' => 2022,
                'plate_number' => 'TOY-123',
                'color' => 'Piros',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 28000.00,
                'status' => 'available',
                'image' => 'https://st2.depositphotos.com/3037725/45775/i/450/depositphotos_457759302-stock-photo-tula-russia-february-2021-toyota.jpg',
                'image_type' => 'link',
                'description' => 'Gazdaságos hibrid autó mindennapi használatra.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:44:34',
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Golf R',
                'category' => 'Hatchback',
                'year' => 2020,
                'plate_number' => 'VWG-888',
                'color' => 'Kék',
                'fuel_type' => 'Dízel',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 24000.00,
                'status' => 'available',
                'image' => 'https://www.goauto.com.au/assets/contents/1b6618eb81ca63feecfb3a249c7e8534e914f480.jpg',
                'image_type' => 'link',
                'description' => 'Kompakt és megbízható autó alacsony fogyasztással.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:47:52',
            ],
            [
                'brand' => 'Skoda',
                'model' => 'Octavia VRs',
                'category' => 'Kombi',
                'year' => 2024,
                'plate_number' => 'SKO-777',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 26000.00,
                'status' => 'available',
                'image' => 'https://cdn.nwi-ms.com/media/hu/C/mc/PV56YD6H/model/front.png?F=5X5X&P=ME&M=9VS@KA6@PJC@PK1@PYB&size=M&background=transparent',
                'image_type' => 'link',
                'description' => 'Tágas csomagtér és családbarát kialakítás.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:47:41',
            ],
            [
                'brand' => 'Ford',
                'model' => 'Focus ST',
                'category' => 'Hatchback',
                'year' => 2023,
                'plate_number' => 'FOR-456',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 22000.00,
                'status' => 'available',
                'image' => 'https://www.autobics.com/wp-content/uploads/2023/03/2023-Ford-Focus-ST-Frozen-White.jpg',
                'image_type' => 'link',
                'description' => 'Kezelhető városi autó, jó ár-érték aránnyal.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:47:30',
            ],
            [
                'brand' => 'Nissan',
                'model' => 'Qashqai',
                'category' => 'SUV',
                'year' => 2021,
                'plate_number' => 'NIS-909',
                'color' => 'Piros',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 33000.00,
                'status' => 'available',
                'image' => 'https://www-europe.nissan-cdn.net/content/dam/Nissan/hu/vehicles/new_qashqai/QQMC-ICE-N-Design.png',
                'image_type' => 'link',
                'description' => 'Magasabb üléspozíció és kényelmes utazás hosszabb távra.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:42:06',
            ],
            [
                'brand' => 'Kia',
                'model' => 'Sportage',
                'category' => 'SUV',
                'year' => 2023,
                'plate_number' => 'KIA-313',
                'color' => 'Zöld',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 34000.00,
                'status' => 'available',
                'image' => 'https://www.kia.com/content/dam/kia/us/en/vehicles/sportage/2026/trims/lx/exterior/10101/360/36.png',
                'image_type' => 'link',
                'description' => 'Modern SUV fejlett biztonsági rendszerekkel.',
                'created_at' => '2026-04-23 09:43:56',
                'updated_at' => '2026-04-23 10:37:26',
            ],
            [
                'brand' => 'Hyundai',
                'model' => 'i30 N',
                'category' => 'Hatchback',
                'year' => 2022,
                'plate_number' => 'HYU-330',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 25000.00,
                'status' => 'available',
                'image' => 'https://d2s8i866417m9.cloudfront.net/photo/39287289/photo/medium-fc29c5f27ae595df81ba14ca3b21704e.png',
                'image_type' => 'link',
                'description' => 'Kényelmes kompakt autó városi használatra.',
                'created_at' => '2026-04-23 09:51:21',
                'updated_at' => '2026-04-23 10:48:09',
            ],
            [
                'brand' => 'Renault',
                'model' => 'Clio',
                'category' => 'Hatchback',
                'year' => 2021,
                'plate_number' => 'REN-221',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 21000.00,
                'status' => 'available',
                'image' => 'https://images.ctfassets.net/3xid768u5joa/67uQojS19sdvMKIy8iRn9m/23c13f6c35f0b44421cf9e02f542e7ce/01._Glacier_White_solid.jpg',
                'image_type' => 'link',
                'description' => 'Kis fogyasztású városi autó, könnyű parkolással.',
                'created_at' => '2026-04-23 09:51:21',
                'updated_at' => '2026-04-23 10:27:49',
            ],
            [
                'brand' => 'Peugeot',
                'model' => '3008',
                'category' => 'SUV',
                'year' => 2022,
                'plate_number' => 'PEU-308',
                'color' => 'Kék',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 34500.00,
                'status' => 'available',
                'image' => 'https://cdn.gablini.hu/uj-autok/modell/nagy/3008-car-selector-855x410-kxM141KdFv.png',
                'image_type' => 'link',
                'description' => 'Családi SUV modern infotainment rendszerrel.',
                'created_at' => '2026-04-23 09:51:21',
                'updated_at' => '2026-04-23 10:28:56',
            ],
            [
                'brand' => 'Opel',
                'model' => 'Astra',
                'category' => 'Kombi',
                'year' => 2020,
                'plate_number' => 'OPE-404',
                'color' => 'Szürke',
                'fuel_type' => 'Dízel',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 23500.00,
                'status' => 'available',
                'image' => 'https://api.vantage-leasing.com/storage/vehicles/VA033807/thumbs_astra-sports-tourer-vast-24b.jpg',
                'image_type' => 'link',
                'description' => 'Tágas kombi hosszabb utazásokhoz.',
                'created_at' => '2026-04-23 09:51:21',
                'updated_at' => '2026-04-23 10:30:41',
            ],
            [
                'brand' => 'Mazda',
                'model' => 'CX-5',
                'category' => 'SUV',
                'year' => 2023,
                'plate_number' => 'MAZ-525',
                'color' => 'Bordó',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 36500.00,
                'status' => 'available',
                'image' => 'https://media-assets.mazda.eu/image/upload/q_auto,f_auto/mazdahu/contentassets/e3f74746ad4a4828b9666eb05cc02401/new_cx-5-exclusiveline-klbceaa_46v-lhd-7-8.png?rnd=4a4c07',
                'image_type' => 'link',
                'description' => 'Prémium érzetű SUV kényelmes futóművel.',
                'created_at' => '2026-04-23 09:51:21',
                'updated_at' => '2026-04-23 10:31:14',
            ],
            [
                'brand' => 'Seat',
                'model' => 'Leon',
                'category' => 'Hatchback',
                'year' => 2021,
                'plate_number' => 'SEA-610',
                'color' => 'Piros',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 22500.00,
                'status' => 'available',
                'image' => 'https://assets.nexuspointapex.co.uk/resize/480/tenant_d9013b5a-4990-4f3e-beec-4e1fc85990eb/media/10062083/seat-leon-15-tsi-evo-fr-sport-euro-6-ss-5dr-8a42ab079cfcb256019d6d0daaf94c8d-69d74be77f3c1.jpg',
                'image_type' => 'link',
                'description' => 'Sportos kompakt modell jó ár-érték aránnyal.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:14:36',
            ],
            [
                'brand' => 'Honda',
                'model' => 'Civic',
                'category' => 'Sedan',
                'year' => 2022,
                'plate_number' => 'HON-917',
                'color' => 'Fekete',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 30500.00,
                'status' => 'available',
                'image' => 'https://autocarpet.hu/img/49420/08-1312/500x500/08-1312.webp?time=1678616538',
                'image_type' => 'link',
                'description' => 'Kényelmes és csendes hibrid szedán.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:15:40',
            ],
            [
                'brand' => 'Suzuki',
                'model' => 'Vitara',
                'category' => 'SUV',
                'year' => 2020,
                'plate_number' => 'SUZ-442',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 25500.00,
                'status' => 'available',
                'image' => 'https://autocarpet.hu/img/49420/78486/500x500/78486.webp?time=1716206595',
                'image_type' => 'link',
                'description' => 'Megbízható SUV mindennapi használatra.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:16:07',
            ],
            [
                'brand' => 'Dacia',
                'model' => 'Duster',
                'category' => 'SUV',
                'year' => 2021,
                'plate_number' => 'DAC-525',
                'color' => 'Narancs',
                'fuel_type' => 'Dízel',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 24500.00,
                'status' => 'available',
                'image' => 'https://w0.peakpx.com/wallpaper/107/490/HD-wallpaper-dacia-duster-crossovers-2018-cars-evolution-new-duster-orange-duster-dacia.jpg',
                'image_type' => 'link',
                'description' => 'Strapabíró modell rosszabb utakra is.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:17:16',
            ],
            [
                'brand' => 'Volvo',
                'model' => 'XC60',
                'category' => 'SUV',
                'year' => 2023,
                'plate_number' => 'VOL-860',
                'color' => 'Szürke',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 44500.00,
                'status' => 'available',
                'image' => 'https://pictures.dealer.com/v/volvocarswesthoustonvcna/1234/2477a5a245a741e8956b7feeba804c8f.png?impolicy=downsize_bkpt&w=410',
                'image_type' => 'link',
                'description' => 'Prémium SUV fejlett biztonsági csomaggal.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:17:56',
            ],
            [
                'brand' => 'Mini',
                'model' => 'Cooper',
                'category' => 'Hatchback',
                'year' => 2022,
                'plate_number' => 'MIN-111',
                'color' => 'Kék',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 4,
                'daily_price' => 29000.00,
                'status' => 'available',
                'image' => 'https://www.shutterstock.com/image-photo/mini-cooper-model-s-german-600nw-2683049133.jpg',
                'image_type' => 'link',
                'description' => 'Kompakt, stílusos városi autó.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:19:56',
            ],
            [
                'brand' => 'Jeep',
                'model' => 'Compass',
                'category' => 'SUV',
                'year' => 2021,
                'plate_number' => 'JEE-909',
                'color' => 'Zöld',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 33500.00,
                'status' => 'available',
                'image' => 'https://www.jeep.hu/content/dam/jeep/crossmarket/compass-my-25/phev/06-defining-your-style/summit/figurines/JEEP-COMPASS-SUMMIT-PHEV-MY25-565x330-TECHNO-GREEN-BR-FIGURINE.png',
                'image_type' => 'link',
                'description' => 'Masszív SUV kényelmes utastérrel.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:20:34',
            ],
            [
                'brand' => 'Fiat',
                'model' => '500X',
                'category' => 'SUV',
                'year' => 2020,
                'plate_number' => 'FIA-500',
                'color' => 'Fehér',
                'fuel_type' => 'Benzin',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 21500.00,
                'status' => 'available',
                'image' => 'https://fiat-wa.com/wp-content/uploads/2018/08/500x_BLANC-GELATO_1450x600px.jpg',
                'image_type' => 'link',
                'description' => 'Kis méretű crossover városi közlekedésre.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:21:02',
            ],
            [
                'brand' => 'Alfa Romeo',
                'model' => 'Giulia',
                'category' => 'Sedan',
                'year' => 2022,
                'plate_number' => 'ALF-777',
                'color' => 'Piros',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 38500.00,
                'status' => 'available',
                'image' => 'https://www.alfaromeo.hu/content/dam/alfa/cross/giulia/white-label-update/figurini/AR-GIULIA-MY24-580X344-TRIM-HP-SPRINT.png',
                'image_type' => 'link',
                'description' => 'Dinamikus szedán olasz karakterrel.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:21:27',
            ],
            [
                'brand' => 'Citroen',
                'model' => 'C5 Aircross',
                'category' => 'SUV',
                'year' => 2023,
                'plate_number' => 'CIT-615',
                'color' => 'Ezüst',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 35500.00,
                'status' => 'available',
                'image' => 'https://www.citroen.hu/content/dam/citroen/master/b2c/models/new-c5-aircross-2025/opening-of-order/trim-cards/new-c5-aircross-you-ice.webp?imwidth=768',
                'image_type' => 'link',
                'description' => 'Kényelmes futású SUV hosszabb utakra.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:22:17',
            ],
            [
                'brand' => 'BMW',
                'model' => 'Z4',
                'category' => 'Cabrio',
                'year' => 2021,
                'plate_number' => 'CAB-404',
                'color' => 'Ezüst',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 2,
                'daily_price' => 41000.00,
                'status' => 'available',
                'image' => 'https://platform.cstatic-images.com/in/v2/stock_photos/5ee55197-aca0-492d-a017-e6dc1e17c0fb/97a6a188-3db0-4659-b9a8-3338dcee047a.png',
                'image_type' => 'link',
                'description' => 'Nyitható tetős sportos cabrio élményautó.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:07:36',
            ],
            [
                'brand' => 'Toyota',
                'model' => 'Hilux',
                'category' => 'Pickup',
                'year' => 2022,
                'plate_number' => 'PIC-202',
                'color' => 'Fehér',
                'fuel_type' => 'Dízel',
                'transmission' => 'Manuális',
                'seats' => 5,
                'daily_price' => 39500.00,
                'status' => 'available',
                'image' => 'https://stimg.cardekho.com/images/car-images/large/Toyota/Hilux/10924/1691990647375/224_super-white_ffffff.jpg?impolicy=resize&imwidth=420',
                'image_type' => 'link',
                'description' => 'Erős pickup nagy raktérrel és terepképességgel.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:22:45',
            ],
            [
                'brand' => 'Subaru',
                'model' => 'Forester',
                'category' => 'Terepjáró',
                'year' => 2023,
                'plate_number' => 'TER-303',
                'color' => 'Zöld',
                'fuel_type' => 'Hibrid',
                'transmission' => 'Automata',
                'seats' => 5,
                'daily_price' => 43000.00,
                'status' => 'available',
                'image' => 'https://di-sitebuilder-assets.dealerinspire.com/Subaru/modelLandingPages/Forester/2024/Exterior/Autumn_Green_Metallic_RFH_TAP_360e_023.png',
                'image_type' => 'link',
                'description' => 'Stabil terepjáró nehezebb útviszonyokra is.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:23:34',
            ],
            [
                'brand' => 'Audi',
                'model' => 'TT',
                'category' => 'Coupe',
                'year' => 2020,
                'plate_number' => 'COU-808',
                'color' => 'Piros',
                'fuel_type' => 'Benzin',
                'transmission' => 'Automata',
                'seats' => 4,
                'daily_price' => 36500.00,
                'status' => 'available',
                'image' => 'https://imgd.aeplcdn.com/370x208/ec/c5/3E/18867/img/m/Audi-TT-Right-Front-Three-Quarter-52278_ol.jpg?t=121521283&t=121521283&q=80',
                'image_type' => 'link',
                'description' => 'Kupé karosszériás sportos modell prémium belsővel.',
                'created_at' => '2026-04-23 10:01:02',
                'updated_at' => '2026-04-23 10:24:18',
            ],
        ];

        Car::query()->upsert(
            $cars,
            ['plate_number'],
            [
                'brand',
                'model',
                'category',
                'year',
                'color',
                'fuel_type',
                'transmission',
                'seats',
                'daily_price',
                'status',
                'image',
                'image_type',
                'description',
                'created_at',
                'updated_at',
            ]
        );

        $reservationSamples = [
            ['email' => 'user@bestrent.com', 'plate' => 'TES-301', 'start_offset' => -12, 'days' => 2, 'status' => 'completed', 'pickup' => 'Budapest', 'dropoff' => 'Budapest', 'notes' => 'Reptéri út'],
            ['email' => 'user@bestrent.com', 'plate' => 'AUD-442', 'start_offset' => -8, 'days' => 3, 'status' => 'completed', 'pickup' => 'Győr', 'dropoff' => 'Győr', 'notes' => 'Üzleti út'],
            ['email' => 'anna@bestrent.com', 'plate' => 'BMW-320', 'start_offset' => -4, 'days' => 2, 'status' => 'active', 'pickup' => 'Szeged', 'dropoff' => 'Szeged', 'notes' => 'Aktív bérlés példa'],
            ['email' => 'peter@bestrent.com', 'plate' => 'MER-200', 'start_offset' => -1, 'days' => 4, 'status' => 'confirmed', 'pickup' => 'Pécs', 'dropoff' => 'Pécs', 'notes' => 'Hétvégi kirándulás'],
            ['email' => 'anna@bestrent.com', 'plate' => 'TOY-123', 'start_offset' => 1, 'days' => 5, 'status' => 'pending', 'pickup' => 'Debrecen', 'dropoff' => 'Debrecen', 'notes' => 'Vár jóváhagyásra'],
            ['email' => 'user@bestrent.com', 'plate' => 'VWG-888', 'start_offset' => 3, 'days' => 2, 'status' => 'pending', 'pickup' => 'Budapest', 'dropoff' => 'Eger', 'notes' => 'Rövid út'],
            ['email' => 'peter@bestrent.com', 'plate' => 'SKO-777', 'start_offset' => 6, 'days' => 3, 'status' => 'confirmed', 'pickup' => 'Miskolc', 'dropoff' => 'Miskolc', 'notes' => 'Családi program'],
            ['email' => 'anna@bestrent.com', 'plate' => 'FOR-456', 'start_offset' => 8, 'days' => 2, 'status' => 'pending', 'pickup' => 'Győr', 'dropoff' => 'Sopron', 'notes' => 'Városnézés'],
            ['email' => 'user@bestrent.com', 'plate' => 'NIS-909', 'start_offset' => 10, 'days' => 4, 'status' => 'confirmed', 'pickup' => 'Budapest', 'dropoff' => 'Balatonfüred', 'notes' => 'Nyaralás'],
            ['email' => 'peter@bestrent.com', 'plate' => 'KIA-313', 'start_offset' => 13, 'days' => 3, 'status' => 'pending', 'pickup' => 'Pécs', 'dropoff' => 'Pécs', 'notes' => 'Céges út'],
            ['email' => 'anna@bestrent.com', 'plate' => 'HYU-330', 'start_offset' => 15, 'days' => 2, 'status' => 'pending', 'pickup' => 'Kecskemét', 'dropoff' => 'Kecskemét', 'notes' => 'Minta foglalás 11'],
            ['email' => 'user@bestrent.com', 'plate' => 'REN-221', 'start_offset' => 17, 'days' => 2, 'status' => 'confirmed', 'pickup' => 'Nyíregyháza', 'dropoff' => 'Nyíregyháza', 'notes' => 'Minta foglalás 12'],
            ['email' => 'peter@bestrent.com', 'plate' => 'PEU-308', 'start_offset' => 19, 'days' => 3, 'status' => 'pending', 'pickup' => 'Szolnok', 'dropoff' => 'Szolnok', 'notes' => 'Minta foglalás 13'],
            ['email' => 'anna@bestrent.com', 'plate' => 'OPE-404', 'start_offset' => 21, 'days' => 4, 'status' => 'pending', 'pickup' => 'Veszprém', 'dropoff' => 'Veszprém', 'notes' => 'Minta foglalás 14'],
            ['email' => 'user@bestrent.com', 'plate' => 'MAZ-525', 'start_offset' => 24, 'days' => 3, 'status' => 'confirmed', 'pickup' => 'Budapest', 'dropoff' => 'Budapest', 'notes' => 'Minta foglalás 15'],
        ];

        foreach ($reservationSamples as $sample) {
            $user = User::query()->where('email', $sample['email'])->first();
            $car = Car::query()->where('plate_number', $sample['plate'])->first();

            if (! $user || ! $car) {
                continue;
            }

            $startDate = now()->addDays($sample['start_offset'])->toDateString();
            $endDate = now()->addDays($sample['start_offset'] + $sample['days'])->toDateString();
            $totalPrice = $car->daily_price * $sample['days'];

            $reservation = Reservation::query()->firstOrCreate([
                'user_id' => $user->id,
                'car_id' => $car->id,
                'start_date' => $startDate,
                'end_date' => $endDate,
            ], [
                'pickup_location' => $sample['pickup'],
                'dropoff_location' => $sample['dropoff'],
                'total_price' => $totalPrice,
                'status' => $sample['status'],
                'notes' => $sample['notes'],
            ]);

            if (in_array($sample['status'], ['completed', 'confirmed', 'active'], true)) {
                $paymentStatus = $sample['status'] === 'completed' ? 'paid' : 'pending';

                Payment::query()->firstOrCreate([
                    'reservation_id' => $reservation->id,
                ], [
                    'user_id' => $user->id,
                    'amount' => $totalPrice,
                    'method' => 'card',
                    'status' => $paymentStatus,
                    'transaction_id' => $paymentStatus === 'paid' ? 'SEED-' . $reservation->id : null,
                    'paid_at' => $paymentStatus === 'paid' ? now()->subDay() : null,
                ]);
            }
        }
    }
}
