<?php

return [
    'locations' => [
        'Budapest Liszt Ferenc Nemzetközi Repülőtér (BUD)',
        'Debrecen Nemzetközi Repülőtér',
        'Keszthely kikötő',
        'Budapest Keleti pályaudvar',
        'Budapest Nyugati pályaudvar',
        'Budapest Déli pályaudvar',
        'Budapest Kelenföld vasútállomás',
        'Győr vasútállomás',
        'Szeged vasútállomás',
        'Pécs vasútállomás',
        'Debrecen vasútállomás',
        'Miskolc Tiszai pályaudvar',
        'Székesfehérvár vasútállomás',
        'Kecskemét vasútállomás',
        'Nyíregyháza vasútállomás',
        'Szolnok vasútállomás',
        'Veszprém vasútállomás',
        'Siófok vasútállomás',
        'Balatonfüred vasútállomás',
        'Sopron vasútállomás',
        'Szombathely vasútállomás',
        'Zalaegerszeg vasútállomás',
        'Kaposvár vasútállomás',
        'Békéscsaba vasútállomás',
        'Eger vasútállomás',
        'Budapest Népliget autóbusz-pályaudvar',
        'Budapest Stadion autóbusz-pályaudvar',
        'Szeged autóbusz-állomás',
        'Pécs autóbusz-állomás',
        'Győr autóbusz-állomás',
        'Eger autóbusz-állomás',
        'Debrecen autóbusz-állomás',
        'Miskolc autóbusz-állomás',
        'Székesfehérvár autóbusz-állomás',
        'Kecskemét autóbusz-állomás',
        'Nyíregyháza autóbusz-állomás',
        'Szolnok autóbusz-állomás',
        'Veszprém autóbusz-állomás',
        'Sopron autóbusz-állomás',
        'Szombathely autóbusz-állomás',
        'Zalaegerszeg autóbusz-állomás',
        'Kaposvár autóbusz-állomás',
        'Békéscsaba autóbusz-állomás',
        'Deák Ferenc tér Budapest',
        'Oktogon Budapest',
        'Blaha Lujza tér Budapest',
        'Kálvin tér Budapest',
        'Batthyány tér Budapest',
        'Clark Ádám tér Budapest',
        'Hősök tere Budapest',
        'Debrecen belváros',
        'Győr belváros',
        'Szeged belváros',
        'Pécs belváros',
        'Miskolc belváros',
        'Kecskemét főtér',
        'Nyíregyháza belváros',
        'Székesfehérvár belváros',
        'Sopron belváros',
        'Szombathely belváros',
        'Zalaegerszeg belváros',
        'Kaposvár belváros',
        'Békéscsaba belváros',
        'Siófok kikötő',
        'Balatonfüred kikötő',
        'Tihany központ',
        'Hévíz látogatói központ',

    ],
];